### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by moore3071** [OSUOSC/command-line-introduction#4]
I propose licensing this under [CC0](https://github.com/github/choosealicense.com/blob/gh-pages/_licenses/cc0-1.0.txt). Awaiting approval from other contributors.

- [x] @moore3071
- [x] @egladman 
- [x] @afuhrtrumpet 
- [x] @meinwald 
- [x] @J3RN

**Comment by afuhrtrumpet** [comment]
Sure.

**Comment by egladman** [comment]
Fine.

**Comment by meinwald** [comment]
Consider the portion I wrote (currently in the "deprecated"
directory) CC0.

**Comment by J3RN** [comment]
Yup. Go for it.
